import type { User, Ticket } from "./types"

// Mock users with different roles
export const mockUsers: User[] = [
  {
    id: 1,
    username: "admin",
    email: "admin@company.com",
    role: "admin",
    createdAt: "2024-01-01T00:00:00Z",
    lastLogin: "2024-12-29T10:00:00Z",
    isActive: true,
  },
  {
    id: 2,
    username: "pm_sarah",
    email: "sarah@company.com",
    role: "project_manager",
    createdAt: "2024-01-15T00:00:00Z",
    lastLogin: "2024-12-29T09:30:00Z",
    isActive: true,
  },
  {
    id: 3,
    username: "dev_john",
    email: "john@company.com",
    role: "developer",
    createdAt: "2024-02-01T00:00:00Z",
    lastLogin: "2024-12-29T08:00:00Z",
    isActive: true,
  },
  {
    id: 4,
    username: "dev_emma",
    email: "emma@company.com",
    role: "developer",
    createdAt: "2024-02-15T00:00:00Z",
    lastLogin: "2024-12-28T16:00:00Z",
    isActive: true,
  },
  {
    id: 5,
    username: "client_mike",
    email: "mike@customer.com",
    role: "client",
    createdAt: "2024-03-01T00:00:00Z",
    lastLogin: "2024-12-29T11:00:00Z",
    isActive: true,
  },
  {
    id: 6,
    username: "client_lisa",
    email: "lisa@customer.com",
    role: "client",
    createdAt: "2024-03-15T00:00:00Z",
    lastLogin: "2024-12-27T14:00:00Z",
    isActive: true,
  },
]

// Mock tickets
export const mockTickets: Ticket[] = [
  {
    id: 1,
    userId: 5,
    query: "Unable to login to the system. Getting 'Invalid credentials' error even with correct password.",
    reply: "Password has been reset. Please check your email for the new temporary password.",
    status: "CLOSED",
    priority: "HIGH",
    assignedDeveloperId: 3,
    assignedBy: 2,
    assignedAt: "2024-12-20T10:00:00Z",
    assignmentNotes: "Urgent - client blocked from system",
    completedAt: "2024-12-20T14:00:00Z",
    completionNotes: "Reset password and verified access",
    createdAt: "2024-12-20T09:00:00Z",
    updatedAt: "2024-12-20T14:00:00Z",
    clientName: "client_mike",
    developerName: "dev_john",
    assignedByName: "pm_sarah",
  },
  {
    id: 2,
    userId: 6,
    query: "Dashboard loading very slowly. Takes more than 30 seconds to load.",
    reply: null,
    status: "IN_PROGRESS",
    priority: "MEDIUM",
    assignedDeveloperId: 4,
    assignedBy: 2,
    assignedAt: "2024-12-28T11:00:00Z",
    assignmentNotes: "Performance issue - check database queries",
    completedAt: null,
    completionNotes: null,
    createdAt: "2024-12-28T10:00:00Z",
    updatedAt: "2024-12-28T11:00:00Z",
    clientName: "client_lisa",
    developerName: "dev_emma",
    assignedByName: "pm_sarah",
  },
  {
    id: 3,
    userId: 5,
    query: "Need to export all reports from last quarter in PDF format.",
    reply: null,
    status: "OPEN",
    priority: "LOW",
    assignedDeveloperId: null,
    assignedBy: null,
    assignedAt: null,
    assignmentNotes: null,
    completedAt: null,
    completionNotes: null,
    createdAt: "2024-12-29T08:00:00Z",
    updatedAt: null,
    clientName: "client_mike",
    developerName: null,
    assignedByName: null,
  },
  {
    id: 4,
    userId: 6,
    query: "Critical bug: Payment processing failing for all transactions.",
    reply: null,
    status: "OPEN",
    priority: "CRITICAL",
    assignedDeveloperId: null,
    assignedBy: null,
    assignedAt: null,
    assignmentNotes: null,
    completedAt: null,
    completionNotes: null,
    createdAt: "2024-12-29T09:00:00Z",
    updatedAt: null,
    clientName: "client_lisa",
    developerName: null,
    assignedByName: null,
  },
  {
    id: 5,
    userId: 5,
    query: "Feature request: Add dark mode to the application.",
    reply: null,
    status: "IN_PROGRESS",
    priority: "LOW",
    assignedDeveloperId: 3,
    assignedBy: 1,
    assignedAt: "2024-12-27T14:00:00Z",
    assignmentNotes: "Nice to have feature",
    completedAt: null,
    completionNotes: null,
    createdAt: "2024-12-25T10:00:00Z",
    updatedAt: "2024-12-27T14:00:00Z",
    clientName: "client_mike",
    developerName: "dev_john",
    assignedByName: "admin",
  },
]

// Credentials for demo (password is same as username for simplicity)
export const mockCredentials: Record<string, string> = {
  admin: "admin",
  pm_sarah: "sarah123",
  dev_john: "john123",
  dev_emma: "emma123",
  client_mike: "mike123",
  client_lisa: "lisa123",
}
